#!/bin/bash

## Get data
STATUS="$(playerctl status)"

## Get status
get_status() {
	if [[ "$STATUS" == "Playing" ]]; then
		echo ""
	else
		echo "喇"
	fi
}

## Get song
get_song() {
	song=$(playerctl metadata title)
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi
}

## Get artist
get_artist() {
	artist=$(playerctl metadata artist)
	if [[ -z "$artist" ]]; then
		echo "Offline"
	else
		echo "$artist"
	fi
}

## Get time
get_time() {
	time=$(playerctl metadata --format "{{ duration(mpris:length - position) }}")
	if [[ -z "$time" ]]; then
		echo "0"
	else
		echo "$time"
	fi
}
get_ctime() {
	ctime=$(playerctl metadata --format "{{ duration(position) }}")
	if [[ -z "$ctime" ]]; then
		echo "0:00"
	else
		echo "$ctime"
	fi
}
get_ttime() {
	ttime=$(playerctl metadata --format "{{ duration(mpris:length) }}")
	if [[ -z "$ttime" ]]; then
		echo "0:00"
	else
		echo "$ttime"
	fi
}

## Get coverd
get_cover() {
	echo $(playerctl -p spotify_player,%any metadata mpris:artUrl)
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	mpc -q toggle
elif [[ "$1" == "--next" ]]; then
	{
		mpc -q next
		get_cover
	}
elif [[ "$1" == "--prev" ]]; then
	{
		mpc -q prev
		get_cover
	}
fi
